#!/usr/bin/env python3

import argparse
import json
import time
from datetime import datetime
from pathlib import Path


def timestamp() -> str:
    return datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")


def load_tasks(path: str):
    file_path = Path(path)
    if not file_path.exists():
        raise FileNotFoundError(f"Tasks file not found: {path}")

    with file_path.open("r", encoding="utf-8") as file:
        data = json.load(file)

    if not isinstance(data, list):
        raise ValueError("Tasks file must contain a JSON array of tasks.")

    return data


def run_task(task: dict):
    name = task.get("name", "unnamed-task")
    action = task.get("action", "noop")
    payload = task.get("payload", {})

    print(f"[{timestamp()}] Running task: {name} ({action})")

    if action == "echo":
        message = payload.get("message", "Hello from the automation starter!")
        print(f"[{timestamp()}] {message}")
        return {"status": "ok", "message": message}

    if action == "write_file":
        output_path = payload.get("path", "output.txt")
        content = payload.get("content", f"Generated by automation starter at {timestamp()}\n")
        Path(output_path).write_text(content, encoding="utf-8")
        print(f"[{timestamp()}] Wrote file: {output_path}")
        return {"status": "ok", "path": output_path}

    if action == "noop":
        print(f"[{timestamp()}] No-op task complete.")
        return {"status": "ok", "message": "no-op"}

    raise ValueError(f"Unsupported action: {action}")


def run_tasks(task_list):
    results = []
    for task in task_list:
        results.append(run_task(task))
    return results


def main():
    parser = argparse.ArgumentParser(description="Basic automation starter")
    parser.add_argument("--tasks", default="tasks.json", help="Path to JSON task list")
    parser.add_argument("--once", action="store_true", help="Run tasks once and exit")
    parser.add_argument("--interval", type=int, default=0, help="Seconds between runs. 0 disables repeating.")
    args = parser.parse_args()

    while True:
        tasks = load_tasks(args.tasks)
        print(f"[{timestamp()}] Starting automation cycle")
        run_tasks(tasks)

        if args.once or args.interval <= 0:
            break

        print(f"[{timestamp()}] Waiting {args.interval} seconds before next cycle...\n")
        time.sleep(args.interval)


if __name__ == "__main__":
    main()
